---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker-dpdk
  labels:
    machineconfiguration.openshift.io/role: worker-dpdk
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values: [ worker, worker-dpdk ]
  paused: true
  maxUnavailable: 10%
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-dpdk: ""
