apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Disconnected Operators Catalog
  image: registry.redhat.io/redhat/redhat-operator-index:v4.22
  publisher: Red Hat
  sourceType: grpc
status:
  connectionState:
    lastObservedState: READY
