apiVersion: operators.coreos.com/v1
kind: Operator
metadata:
  name: cluster-logging.openshift-logging
status:
  components:
    refs:
    - conditions:
      - reason: InstallSucceeded
        status: 'True'
        type: Succeeded
      kind: ClusterServiceVersion
      name: cluster-logging.v6.6.1
      namespace: openshift-logging
