apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    operatorframework.io/bundle-unpack-min-retry-interval: 10m
  name: sriov-network-operators
  namespace: openshift-sriov-network-operator
spec:
  targetNamespaces:
  - openshift-sriov-network-operator
