apiVersion: nodetopology.openshift.io/v1
kind: NUMAResourcesScheduler
metadata:
  name: numaresourcesscheduler
spec:
  imageSpec: registry.example.com/openshift4/noderesourcetopology-scheduler-rhel9@sha256:aa00bb11cc22dd33ee44ff55ab66cd77ef88bc1234123bbd5aa789aabb8c1234
  schedulerName: topo-aware-scheduler
