apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: sizing-master
spec:
  kubeletConfig:
    systemReserved:
      memory: 30Gi
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ''
