apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  annotations:
    kubeletconfig.experimental: '{"allowedUnsafeSysctls":["net.ipv6.conf.all.accept_ra"],"maxPods":750}

      '
  name: controlplane
spec:
  additionalKernelArgs:
  - module_blacklist=irdma
  cpu:
    isolated: 50-287,338-575
    reserved: 0-49,288-337
  globallyDisableIrqLoadBalancing: false
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 32
      size: 1G
  net:
    userLevelNetworking: false
  nodeSelector:
    node-role.kubernetes.io/master: ''
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: false
    perPodPowerManagement: true
    realTime: false
