apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  annotations:
    kubeletconfig.experimental: '{"allowedUnsafeSysctls":["net.ipv6.conf.all.accept_ra"],"maxPods":750}

      '
  name: controlplane
spec:
  additionalKernelArgs:
  - module_blacklist=irdma
  cpu:
    isolated: 25-143,169-287,313-431,457-575
    reserved: 0-24,144-168,288-312,432-456
  globallyDisableIrqLoadBalancing: false
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 32
      size: 1G
  net:
    userLevelNetworking: false
  nodeSelector:
    node-role.kubernetes.io/master: ''
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: false
    perPodPowerManagement: true
    realTime: false
