apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  annotations:
    kubeletconfig.experimental: '{"allowedUnsafeSysctls":["net.ipv6.conf.all.accept_ra"],"maxPods":750}

      '
  name: worker
spec:
  additionalKernelArgs:
  - module_blacklist=irdma
  cpu:
    isolated: 1,3,5,7,9,11,13,15,17,19-55,57,59,61,63,65,67,69,71,73,75-111
    reserved: 0,2,4,6,8,10,12,14,16,18,56,58,60,62,64,66,68,70,72,74
  globallyDisableIrqLoadBalancing: false
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 32
      size: 1G
  net:
    userLevelNetworking: false
  nodeSelector:
    node-role.kubernetes.io/worker-r750: ''
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: false
    perPodPowerManagement: true
    realTime: false
