apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-r750
  name: worker-r750
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - worker-r750
  maxUnavailable: 100%
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-r750: ''
  paused: false
status:
  conditions:
  - status: 'True'
    type: Updated
  - status: 'False'
    type: Updating
