apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-core-upgrade-ocp-19
  namespace: ztp-core-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-core-upgrade-ocp-19
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: core-upgrade-ocp-19
