apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-core-upgrade-ocp-5-0
  namespace: ztp-core-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-core-upgrade-ocp-5-0
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: core-upgrade-ocp-5-0
