apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-core-cluster-config-4.20
  namespace: ztp-core-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-core-cluster-config-4.20
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: core-cluster-config-4.20
