apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-core-operator-config-5-0
  namespace: ztp-core-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          common: core
          version: '5.0'
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
