apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-core-custom-mcp-set-maxavailable
  namespace: ztp-core-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-core-custom-mcp-set-maxavailable
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: core-custom-mcp-set-maxavailable
