apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-config-monitoring-4.20
  namespace: ztp-core-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-config-monitoring-4.20
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: config-monitoring-4.20
