apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-core-operator-subs-4.22
  namespace: ztp-core-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-core-operator-subs-4.22
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: core-operator-subs-4.22
