# required
# count: 1-N
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool
  namespace: metallb-system
  annotations:
    metallb.universe.tf/address-pool: address-pool
spec:
  ##############
  # Expected variation in this configuration
  addresses:
  - 3.3.3.0/24
  autoAssign: true
  ##############
