# optional (though expected in all deployments)
# count: 0-N
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vm00001-vf
  namespace: openshift-sriov-network-operator
spec:
  deviceType: vfio-pci
  externallyManaged: false
  nicSelector:
    deviceID: "159b"
    pfNames:
    - ens1f0
    - ens1f1
    rootDevices:
    - 0000:4b:00.0
    - 0000:4b:00.1
    vendor: "8086"
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  numVfs: 128
  priority: 99
  # excludeTopology: true
  resourceName: intelnics2
