# optional (though expected in all deployments)
# count: 0-N
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vm00001-vf
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  externallyManaged: false
  nicSelector:
    deviceID: "10c9"
    pfNames:
    - enp4s0
    - enp5s0
    - enp6s0
    - enp7s0
    - enp8s0
    - enp9s0
    - enp10s0
    - enp11s0
    rootDevices:
    - 0000:04:00.0
    - 0000:05:00.0
    - 0000:06:00.0
    - 0000:07:00.0
    - 0000:08:00.0
    - 0000:09:00.0
    - 0000:0a:00.0
    - 0000:0b:00.0
    vendor: "8086"
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  numVfs: 7
  priority: 99
  # excludeTopology: true
  resourceName: intelnics2
